name: first worflow
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: cloning Code
      - run: git clone https://github.com/Dc-github25/Dc-repo.git
      - uses: actions/setup-node@v4     
        with:
          node-version: '8'
      - name: install dependencies
      - run: npm ci
      - run: echo "build is done"
         