name: first worflow
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # - run: echo "Triggered by: ${{ github.event_name }} https://github.com/Dc-github25/Dc-repo.git"
      - uses: actions/setup-node@v4
        with:
          node-version: '8'
      - run: |
          echo "build is done"
          echo "Triggered by: ${{ github.rerepository}}"