name: first worflow
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - name: cloning Code
      #   run: git clone https://github.com/${{github.repository}}.git
      - name: Checkout code
        uses: actions/checkout@v3
       
      - uses: actions/setup-node@v4     
        with:
          node-version: '16'
      - name: install dependencies
        run: npm install -f
      - name: check build
        run: |
         echo "build is done"
         echo ${{ github.repository }}
      - name: Install Angular CLI
        run: npm install -g @angular/cli@8.3.29
      - run : ng build --prod
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: dist
         