name: first worflow
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: cloning Code
        run: git clone https://github.com/${{ github.repository }}.git
       
      - uses: actions/setup-node@v4     
        with:
          node-version: '8'
      - name: install dependencies
        run: npm install
      - run: |
         echo "build is done"
         echo ${{ github.repository }}
      - name: Install Angular CLI
        run: npm install -g @angular/cli
      - run : ng build --prod
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: dist
         